### ISSUE TITLE
 Missing required option 'device'

### ISSUE THREAD

**Issue by 532910** [mercenaruss/zigstar_addons#31]
ZigStar TI CC2652P7 firmware flasher addon for UZG-01
version: 0.2.0

```
device: null
network_device: IP:6638
usb_mode: false
coordinator_fw: true
router_fw: false
firmware_url: ""
trigger_bsl: true
```

Failed to save add-on configuration, Missing required option 'device' in ZigStar TI CC2652P7 FW Flasher (193f5383_zigstar-cc2652p7-flasher). Got {'device': None, 'network_device': 'IP:6638', 'usb_mode': False, 'coordinator_fw': True, 'router_fw': False, 'firmware_url': '', 'trigger_bsl': True}

**Comment by mercenaruss** [comment]
add please:
device: /dev/ttyS1 or any words to save settings.

**Comment by 532910** [comment]
Yep, I have read the note and believe it must not be required to enter some word to make soft happy. Please reopen.

**Comment by 532910** [comment]
I believe this is an issue and should be fixed.

**Comment by mercenaruss** [comment]
Unfortunately i dont have a solution for this.

**Comment by davlaw** [comment]
still an issue

![Screenshot from 2024-08-25 16-33-21](https://github.com/user-attachments/assets/5963e96f-1a9d-431f-a3e7-3307287723ef)

**Comment by latek0** [comment]
Same problem

<img width="790" alt="Image" src="https://github.com/user-attachments/assets/6b37ba0c-af41-4daf-800d-7bb4f47fb4fc" />

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/62e754f6-fa06-48e9-a272-a190db1842e3" />
